Common: Make DB.CreateFile() not require SQL CE DLLs
This fixes the following exception from applications that don't deploy this DLL:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
   at ShomreiTorah.Common.DB.CreateFile(String filePath, DatabaseFile format)